"""Skill taxonomy dictionary for extracting real skills from job descriptions.

Uses word-boundary-aware matching against a curated dictionary of ~600 skills
with aliases (e.g., "js" -> "JavaScript", "k8s" -> "Kubernetes").

Cost: $0. Speed: instant. Catches 60-70% of skills in typical job postings.
"""

from __future__ import annotations

import re

# Canonical skill name -> set of aliases (all lowercase).
# The canonical name itself is also matched (lowercased).
_SKILL_ALIASES: dict[str, set[str]] = {
    # --- Programming Languages ---
    "Python": {"python", "python3", "python2"},
    "JavaScript": {"javascript", "js", "ecmascript", "es6", "es2015"},
    "TypeScript": {"typescript", "ts"},
    "Java": {"java"},
    "C#": {"c#", "csharp", "c-sharp"},
    "C++": {"c++", "cpp"},
    "C": set(),  # handled specially — requires word boundary
    "Go": {"golang"},
    "Rust": {"rust", "rustlang"},
    "Ruby": {"ruby"},
    "PHP": {"php"},
    "Swift": {"swift"},
    "Kotlin": {"kotlin"},
    "Scala": {"scala"},
    "R": set(),  # handled specially
    "MATLAB": {"matlab"},
    "Perl": {"perl"},
    "Haskell": {"haskell"},
    "Elixir": {"elixir"},
    "Erlang": {"erlang"},
    "Clojure": {"clojure"},
    "Dart": {"dart"},
    "Lua": {"lua"},
    "Julia": {"julia"},
    "Objective-C": {"objective-c", "objc", "obj-c"},
    "Assembly": {"assembly", "asm"},
    "COBOL": {"cobol"},
    "Fortran": {"fortran"},
    "Groovy": {"groovy"},
    "F#": {"f#", "fsharp"},
    "Visual Basic": {"visual basic", "vb.net", "vba", "vbscript"},
    "Shell Scripting": {"bash", "shell scripting", "shell", "zsh", "powershell"},
    "SQL": {"sql"},
    "PL/SQL": {"pl/sql", "plsql"},
    "T-SQL": {"t-sql", "tsql"},
    "Solidity": {"solidity"},
    # --- Frontend Frameworks ---
    "React": {"react", "reactjs", "react.js"},
    "Angular": {"angular", "angularjs", "angular.js"},
    "Vue.js": {"vue", "vuejs", "vue.js"},
    "Svelte": {"svelte", "sveltekit"},
    "Next.js": {"next.js", "nextjs", "next"},
    "Nuxt.js": {"nuxt", "nuxtjs", "nuxt.js"},
    "Remix": {"remix"},
    "Gatsby": {"gatsby", "gatsbyjs"},
    "Ember.js": {"ember", "emberjs", "ember.js"},
    "Backbone.js": {"backbone", "backbonejs", "backbone.js"},
    "jQuery": {"jquery"},
    "Bootstrap": {"bootstrap"},
    "Tailwind CSS": {"tailwind", "tailwindcss", "tailwind css"},
    "Material UI": {"material ui", "mui", "material-ui"},
    "Chakra UI": {"chakra ui", "chakra-ui"},
    "Ant Design": {"ant design", "antd"},
    "Styled Components": {"styled-components", "styled components"},
    "SASS/SCSS": {"sass", "scss"},
    "LESS": {"less"},
    "CSS": {"css", "css3"},
    "HTML": {"html", "html5"},
    "WebGL": {"webgl"},
    "Three.js": {"three.js", "threejs"},
    "D3.js": {"d3", "d3.js", "d3js"},
    "Webpack": {"webpack"},
    "Vite": {"vite"},
    "Babel": {"babel"},
    "ESLint": {"eslint"},
    "Prettier": {"prettier"},
    "Storybook": {"storybook"},
    # --- Backend Frameworks ---
    "Node.js": {"node", "nodejs", "node.js"},
    "Express.js": {"express", "expressjs", "express.js"},
    "FastAPI": {"fastapi"},
    "Django": {"django"},
    "Flask": {"flask"},
    "Spring": {"spring", "spring boot", "springboot", "spring framework"},
    "Spring Boot": {"spring boot", "springboot"},
    "Ruby on Rails": {"rails", "ruby on rails", "ror"},
    "Laravel": {"laravel"},
    "ASP.NET": {"asp.net", "aspnet", "asp.net core", ".net core", "dotnet"},
    ".NET": {".net", "dotnet", ".net framework"},
    "NestJS": {"nestjs", "nest.js"},
    "Fastify": {"fastify"},
    "Koa": {"koa", "koajs"},
    "Gin": {"gin"},
    "Echo": set(),
    "Fiber": set(),
    "Phoenix": {"phoenix"},
    "Actix": {"actix"},
    "Rocket": set(),
    "gRPC": {"grpc", "g-rpc"},
    "GraphQL": {"graphql"},
    "REST API": {"rest", "restful", "rest api", "restful api"},
    "WebSocket": {"websocket", "websockets", "ws"},
    "OAuth": {"oauth", "oauth2", "oauth 2.0"},
    "JWT": {"jwt", "json web token"},
    # --- Databases ---
    "PostgreSQL": {"postgresql", "postgres", "psql"},
    "MySQL": {"mysql"},
    "MariaDB": {"mariadb"},
    "SQLite": {"sqlite"},
    "SQL Server": {"sql server", "mssql", "microsoft sql server"},
    "Oracle Database": {"oracle", "oracle db", "oracle database"},
    "MongoDB": {"mongodb", "mongo"},
    "Redis": {"redis"},
    "Elasticsearch": {"elasticsearch", "elastic search", "elastic"},
    "Cassandra": {"cassandra"},
    "DynamoDB": {"dynamodb"},
    "CouchDB": {"couchdb"},
    "Neo4j": {"neo4j"},
    "InfluxDB": {"influxdb"},
    "TimescaleDB": {"timescaledb"},
    "Memcached": {"memcached"},
    "Firebase": {"firebase", "firestore"},
    "Supabase": {"supabase"},
    "PlanetScale": {"planetscale"},
    "CockroachDB": {"cockroachdb"},
    "Snowflake": {"snowflake"},
    "BigQuery": {"bigquery", "big query"},
    "Redshift": {"redshift"},
    "ClickHouse": {"clickhouse"},
    "Pinecone": {"pinecone"},
    "Weaviate": {"weaviate"},
    "Milvus": {"milvus"},
    "pgvector": {"pgvector"},
    # --- Cloud Platforms ---
    "AWS": {"aws", "amazon web services"},
    "Azure": {"azure", "microsoft azure"},
    "Google Cloud": {"gcp", "google cloud", "google cloud platform"},
    "Heroku": {"heroku"},
    "Vercel": {"vercel"},
    "Netlify": {"netlify"},
    "DigitalOcean": {"digitalocean", "digital ocean"},
    "Cloudflare": {"cloudflare"},
    "Linode": {"linode"},
    # --- AWS Services ---
    "AWS Lambda": {"lambda", "aws lambda"},
    "AWS EC2": {"ec2", "aws ec2"},
    "AWS S3": {"s3", "aws s3"},
    "AWS ECS": {"ecs", "aws ecs"},
    "AWS EKS": {"eks", "aws eks"},
    "AWS RDS": {"rds", "aws rds"},
    "AWS SQS": {"sqs", "aws sqs"},
    "AWS SNS": {"sns", "aws sns"},
    "AWS CloudFormation": {"cloudformation", "aws cloudformation"},
    "AWS CDK": {"aws cdk", "cdk"},
    "AWS Step Functions": {"step functions", "aws step functions"},
    "AWS API Gateway": {"api gateway", "aws api gateway"},
    "AWS Cognito": {"cognito", "aws cognito"},
    "AWS Fargate": {"fargate", "aws fargate"},
    "AWS Glue": {"aws glue"},
    "AWS Kinesis": {"kinesis", "aws kinesis"},
    "AWS SageMaker": {"sagemaker", "aws sagemaker"},
    # --- DevOps & Infrastructure ---
    "Docker": {"docker"},
    "Kubernetes": {"kubernetes", "k8s"},
    "Terraform": {"terraform"},
    "Ansible": {"ansible"},
    "Puppet": {"puppet"},
    "Chef": set(),
    "Vagrant": {"vagrant"},
    "Helm": {"helm", "helm charts"},
    "ArgoCD": {"argocd", "argo cd"},
    "Jenkins": {"jenkins"},
    "GitHub Actions": {"github actions"},
    "GitLab CI": {"gitlab ci", "gitlab ci/cd"},
    "CircleCI": {"circleci", "circle ci"},
    "Travis CI": {"travis ci", "travis"},
    "TeamCity": {"teamcity"},
    "Bamboo": {"bamboo"},
    "Azure DevOps": {"azure devops", "azure pipelines"},
    "Buildkite": {"buildkite"},
    "Drone CI": {"drone ci", "drone"},
    "Nginx": {"nginx"},
    "Apache": {"apache", "httpd"},
    "HAProxy": {"haproxy"},
    "Consul": {"consul"},
    "Vault": {"vault", "hashicorp vault"},
    "Istio": {"istio"},
    "Envoy": {"envoy"},
    "Linkerd": {"linkerd"},
    "Prometheus": {"prometheus"},
    "Grafana": {"grafana"},
    "Datadog": {"datadog"},
    "New Relic": {"new relic", "newrelic"},
    "Splunk": {"splunk"},
    "ELK Stack": {"elk", "elk stack"},
    "Kibana": {"kibana"},
    "Logstash": {"logstash"},
    "PagerDuty": {"pagerduty"},
    "Sentry": {"sentry"},
    "Nagios": {"nagios"},
    "Zabbix": {"zabbix"},
    # --- Version Control ---
    "Git": {"git"},
    "GitHub": {"github"},
    "GitLab": {"gitlab"},
    "Bitbucket": {"bitbucket"},
    "SVN": {"svn", "subversion"},
    # --- Testing ---
    "Jest": {"jest"},
    "Mocha": {"mocha"},
    "Cypress": {"cypress"},
    "Selenium": {"selenium", "selenium webdriver"},
    "Playwright": {"playwright"},
    "Puppeteer": {"puppeteer"},
    "pytest": {"pytest"},
    "unittest": {"unittest"},
    "JUnit": {"junit"},
    "TestNG": {"testng"},
    "RSpec": {"rspec"},
    "Cucumber": {"cucumber"},
    "Postman": {"postman"},
    "Vitest": {"vitest"},
    "Testing Library": {"testing library", "react testing library"},
    "Enzyme": {"enzyme"},
    "Jasmine": {"jasmine"},
    "Chai": {"chai"},
    "Supertest": {"supertest"},
    "k6": {"k6"},
    "JMeter": {"jmeter"},
    "Locust": {"locust"},
    "Gatling": {"gatling"},
    # --- Data & ML ---
    "Machine Learning": {"machine learning", "ml"},
    "Deep Learning": {"deep learning", "dl"},
    "Natural Language Processing": {"nlp", "natural language processing"},
    "Computer Vision": {"computer vision", "cv"},
    "TensorFlow": {"tensorflow", "tf"},
    "PyTorch": {"pytorch"},
    "Keras": {"keras"},
    "scikit-learn": {"scikit-learn", "sklearn", "scikit learn"},
    "Pandas": {"pandas"},
    "NumPy": {"numpy"},
    "SciPy": {"scipy"},
    "Matplotlib": {"matplotlib"},
    "Seaborn": {"seaborn"},
    "Plotly": {"plotly"},
    "Jupyter": {"jupyter", "jupyter notebook", "jupyter notebooks"},
    "Apache Spark": {"spark", "pyspark", "apache spark"},
    "Hadoop": {"hadoop"},
    "Hive": {"hive"},
    "Airflow": {"airflow", "apache airflow"},
    "dbt": {"dbt"},
    "Databricks": {"databricks"},
    "MLflow": {"mlflow"},
    "Kubeflow": {"kubeflow"},
    "Hugging Face": {"hugging face", "huggingface", "transformers"},
    "OpenAI API": {"openai", "openai api", "chatgpt api"},
    "LangChain": {"langchain"},
    "LLM": {"llm", "large language model", "large language models"},
    "RAG": {"rag", "retrieval augmented generation"},
    "Generative AI": {"generative ai", "genai", "gen ai"},
    "Prompt Engineering": {"prompt engineering"},
    "ONNX": {"onnx"},
    "XGBoost": {"xgboost"},
    "LightGBM": {"lightgbm"},
    "CatBoost": {"catboost"},
    "Feature Engineering": {"feature engineering"},
    "ETL": {"etl"},
    "Data Pipeline": {"data pipeline", "data pipelines"},
    "Data Warehousing": {"data warehousing", "data warehouse"},
    "Data Modeling": {"data modeling"},
    "Data Governance": {"data governance"},
    # --- Mobile ---
    "React Native": {"react native"},
    "Flutter": {"flutter"},
    "SwiftUI": {"swiftui"},
    "UIKit": {"uikit"},
    "Jetpack Compose": {"jetpack compose"},
    "Xamarin": {"xamarin"},
    "Ionic": {"ionic"},
    "Expo": {"expo"},
    "Android": {"android"},
    "iOS": {"ios"},
    "Xcode": {"xcode"},
    "Android Studio": {"android studio"},
    "CocoaPods": {"cocoapods"},
    "Gradle": {"gradle"},
    "Maven": {"maven"},
    # --- Message Queues & Streaming ---
    "Kafka": {"kafka", "apache kafka"},
    "RabbitMQ": {"rabbitmq"},
    "Apache Pulsar": {"pulsar", "apache pulsar"},
    "NATS": {"nats"},
    "Celery": {"celery"},
    "RQ": {"rq", "redis queue"},
    "Sidekiq": {"sidekiq"},
    "Bull": {"bull", "bullmq"},
    "ZeroMQ": {"zeromq", "zmq"},
    # --- Design & UI Tools ---
    "Figma": {"figma"},
    "Sketch": {"sketch"},
    "Adobe XD": {"adobe xd"},
    "InVision": {"invision"},
    "Zeplin": {"zeplin"},
    "Adobe Photoshop": {"photoshop", "adobe photoshop"},
    "Adobe Illustrator": {"illustrator", "adobe illustrator"},
    "Canva": {"canva"},
    # --- CRM & Business Tools ---
    "Salesforce": {"salesforce", "sfdc"},
    "HubSpot": {"hubspot"},
    "Zendesk": {"zendesk"},
    "ServiceNow": {"servicenow"},
    "SAP": {"sap"},
    "Workday": {"workday"},
    "Jira": {"jira"},
    "Confluence": {"confluence"},
    "Asana": {"asana"},
    "Trello": {"trello"},
    "Monday.com": {"monday.com"},
    "Notion": {"notion"},
    "Linear": {"linear"},
    "Slack": set(),
    # --- Data Visualization ---
    "Tableau": {"tableau"},
    "Power BI": {"power bi", "powerbi"},
    "Looker": {"looker"},
    "Metabase": {"metabase"},
    "Superset": {"superset", "apache superset"},
    "QuickSight": {"quicksight", "amazon quicksight"},
    # --- Security ---
    "OWASP": {"owasp"},
    "SOC 2": {"soc 2", "soc2"},
    "HIPAA": {"hipaa"},
    "PCI DSS": {"pci dss", "pci"},
    "GDPR": {"gdpr"},
    "Penetration Testing": {"penetration testing", "pen testing", "pentest"},
    "SIEM": {"siem"},
    "WAF": {"waf"},
    "IAM": {"iam"},
    "SSO": {"sso", "single sign-on"},
    "SAML": {"saml"},
    "LDAP": {"ldap"},
    "Active Directory": {"active directory", "ad"},
    "Okta": {"okta"},
    "Auth0": {"auth0"},
    "CrowdStrike": {"crowdstrike"},
    "Snyk": {"snyk"},
    "SonarQube": {"sonarqube"},
    # --- Methodologies & Practices ---
    "Agile": {"agile"},
    "Scrum": {"scrum"},
    "Kanban": {"kanban"},
    "CI/CD": {"ci/cd", "cicd", "ci cd", "continuous integration", "continuous deployment", "continuous delivery"},
    "DevOps": {"devops"},
    "SRE": {"sre", "site reliability engineering"},
    "TDD": {"tdd", "test-driven development", "test driven development"},
    "BDD": {"bdd", "behavior-driven development"},
    "Microservices": {"microservices", "micro-services"},
    "Event-Driven Architecture": {"event-driven", "event driven architecture", "eda"},
    "Domain-Driven Design": {"ddd", "domain-driven design", "domain driven design"},
    "CQRS": {"cqrs"},
    "Event Sourcing": {"event sourcing"},
    "Design Patterns": {"design patterns"},
    "System Design": {"system design"},
    "API Design": {"api design"},
    "Technical Writing": {"technical writing"},
    "Code Review": {"code review", "code reviews"},
    "Pair Programming": {"pair programming"},
    # --- Networking & Protocols ---
    "TCP/IP": {"tcp/ip", "tcp", "ip"},
    "HTTP": {"http", "https"},
    "DNS": {"dns"},
    "CDN": {"cdn"},
    "Load Balancing": {"load balancing", "load balancer"},
    "VPN": {"vpn"},
    "SSL/TLS": {"ssl", "tls", "ssl/tls"},
    # --- OS & Platforms ---
    "Linux": {"linux"},
    "Ubuntu": {"ubuntu"},
    "CentOS": {"centos"},
    "RHEL": {"rhel", "red hat"},
    "Windows Server": {"windows server"},
    "macOS": {"macos"},
    # --- Serialization & Formats ---
    "JSON": {"json"},
    "XML": {"xml"},
    "YAML": {"yaml", "yml"},
    "Protocol Buffers": {"protobuf", "protocol buffers"},
    "Avro": {"avro"},
    "Parquet": {"parquet"},
    "CSV": {"csv"},
    # --- ORMs & Database Tools ---
    "SQLAlchemy": {"sqlalchemy"},
    "Prisma": {"prisma"},
    "Sequelize": {"sequelize"},
    "TypeORM": {"typeorm"},
    "Hibernate": {"hibernate"},
    "Mongoose": {"mongoose"},
    "Alembic": {"alembic"},
    "Flyway": {"flyway"},
    "Liquibase": {"liquibase"},
    # --- Architecture & Infra ---
    "Serverless": {"serverless"},
    "Edge Computing": {"edge computing"},
    "WebAssembly": {"wasm", "webassembly"},
    "Service Mesh": {"service mesh"},
    "API Gateway": {"api gateway"},
    # --- Analytics & Marketing ---
    "Google Analytics": {"google analytics", "ga4"},
    "Segment": {"segment"},
    "Mixpanel": {"mixpanel"},
    "Amplitude": {"amplitude"},
    "A/B Testing": {"a/b testing", "ab testing", "a/b test"},
    # --- Payment ---
    "Stripe": {"stripe"},
    "PayPal": {"paypal"},
    "Braintree": {"braintree"},
    "Plaid": {"plaid"},
    # --- Content Management ---
    "WordPress": {"wordpress"},
    "Contentful": {"contentful"},
    "Sanity": {"sanity"},
    "Strapi": {"strapi"},
    "Drupal": {"drupal"},
    "Shopify": {"shopify"},
    "Magento": {"magento"},
    # --- Collaboration ---
    "Swagger": {"swagger", "openapi", "open api"},
    "Postman": {"postman"},
    # --- Certifications (as skills) ---
    "AWS Certified": {"aws certified", "aws certification"},
    "Azure Certified": {"azure certified", "azure certification"},
    "Google Cloud Certified": {"google cloud certified"},
    "PMP": {"pmp"},
    "Certified Scrum Master": {"csm", "certified scrum master"},
    "CISSP": {"cissp"},
    "CompTIA Security+": {"security+", "comptia security"},
    "CKA": {"cka", "certified kubernetes administrator"},
    # --- Soft / Domain Skills ---
    "Project Management": {"project management"},
    "Product Management": {"product management"},
    "Data Analysis": {"data analysis"},
    "Data Science": {"data science"},
    "Business Intelligence": {"business intelligence", "bi"},
    "UX Design": {"ux design", "ux", "user experience"},
    "UI Design": {"ui design", "ui", "user interface design"},
    "UX Research": {"ux research", "user research"},
    "Accessibility": {"accessibility", "a11y", "wcag"},
    "Responsive Design": {"responsive design", "responsive"},
    "Cross-Browser Testing": {"cross-browser", "cross browser testing"},
    "Performance Optimization": {"performance optimization", "performance tuning"},
    "SEO": {"seo", "search engine optimization"},
    "Content Strategy": {"content strategy"},
    "Copywriting": {"copywriting"},
    "Digital Marketing": {"digital marketing"},
    "Growth Hacking": {"growth hacking"},
    "Customer Success": {"customer success"},
    "Technical Support": {"technical support"},
    "Solutions Architecture": {"solutions architecture", "solutions architect"},
    "Enterprise Architecture": {"enterprise architecture"},
    "Cloud Architecture": {"cloud architecture"},
    "Data Engineering": {"data engineering"},
    "ML Engineering": {"ml engineering", "machine learning engineering"},
    "Platform Engineering": {"platform engineering"},
    "Release Engineering": {"release engineering"},
    "Incident Management": {"incident management"},
    "Change Management": {"change management"},
    "Risk Management": {"risk management"},
    "Vendor Management": {"vendor management"},
    "Stakeholder Management": {"stakeholder management"},
    "Budget Management": {"budget management"},
    "Team Leadership": {"team leadership", "team lead"},
    "Mentoring": {"mentoring", "mentorship"},
    "Cross-Functional Collaboration": {"cross-functional", "cross functional"},
    "Strategic Planning": {"strategic planning"},
    "Requirements Gathering": {"requirements gathering", "requirements analysis"},
    "Business Analysis": {"business analysis"},
    "Process Improvement": {"process improvement"},
    "Lean": {"lean"},
    "Six Sigma": {"six sigma"},
    "ITIL": {"itil"},
    "Supply Chain": {"supply chain"},
    "ERP": {"erp"},
    "CRM": {"crm"},
    "Financial Modeling": {"financial modeling"},
    "Forecasting": {"forecasting"},
    "Reporting": {"reporting"},
    "Compliance": {"compliance"},
    "Regulatory": {"regulatory"},
    "Auditing": {"auditing"},
    "Quality Assurance": {"quality assurance", "qa"},
    "Automation Testing": {"automation testing", "test automation", "automated testing"},
    "Manual Testing": {"manual testing"},
    "Load Testing": {"load testing"},
    "Regression Testing": {"regression testing"},
    "Integration Testing": {"integration testing"},
    "Unit Testing": {"unit testing"},
    "End-to-End Testing": {"end-to-end testing", "e2e testing", "e2e"},
    "API Testing": {"api testing"},
    "Mobile Testing": {"mobile testing"},
    "Performance Testing": {"performance testing"},
    "Security Testing": {"security testing"},
    "Chaos Engineering": {"chaos engineering"},
    "Feature Flags": {"feature flags", "feature toggles"},
    "Blue-Green Deployment": {"blue-green deployment", "blue green"},
    "Canary Deployment": {"canary deployment", "canary release"},
    "Infrastructure as Code": {"infrastructure as code", "iac"},
    "Configuration Management": {"configuration management"},
    "Observability": {"observability"},
    "Distributed Systems": {"distributed systems"},
    "High Availability": {"high availability", "ha"},
    "Disaster Recovery": {"disaster recovery", "dr"},
    "Capacity Planning": {"capacity planning"},
    "Cost Optimization": {"cost optimization"},
    "FinOps": {"finops"},
    "Blockchain": {"blockchain"},
    "Web3": {"web3"},
    "Smart Contracts": {"smart contracts"},
    "NFT": {"nft"},
    "Cryptocurrency": {"cryptocurrency", "crypto"},
    "IoT": {"iot", "internet of things"},
    "Embedded Systems": {"embedded systems", "embedded"},
    "RTOS": {"rtos"},
    "Robotics": {"robotics"},
    "AR/VR": {"ar/vr", "augmented reality", "virtual reality", "ar", "vr"},
    "Game Development": {"game development", "game dev", "gamedev"},
    "Unity": {"unity", "unity3d"},
    "Unreal Engine": {"unreal", "unreal engine"},
    "OpenCV": {"opencv"},
}

# Build reverse lookup: lowercase alias -> canonical name.
_ALIAS_TO_CANONICAL: dict[str, str] = {}
for _canonical, _aliases in _SKILL_ALIASES.items():
    _lower_canonical = _canonical.lower()
    _ALIAS_TO_CANONICAL[_lower_canonical] = _canonical
    for _alias in _aliases:
        _ALIAS_TO_CANONICAL[_alias] = _canonical

# Sort aliases by length descending so longer phrases match first
# (e.g., "react native" before "react").
_SORTED_ALIASES = sorted(_ALIAS_TO_CANONICAL.keys(), key=len, reverse=True)

# Pre-compile regex patterns for each alias.
# Single-letter / very short aliases (C, R) use strict word boundaries.
_ALIAS_PATTERNS: list[tuple[re.Pattern, str]] = []
for _alias in _SORTED_ALIASES:
    _canonical = _ALIAS_TO_CANONICAL[_alias]
    # Escape for regex (handles +, #, ., / etc.)
    _escaped = re.escape(_alias)
    # For single-char aliases like "c" or "r", require stricter boundaries
    # to avoid matching inside words like "create" or "regular".
    if len(_alias) <= 2 and _alias.isalpha():
        _pattern = re.compile(
            r"(?<![a-zA-Z])" + _escaped + r"(?![a-zA-Z])", re.IGNORECASE
        )
    else:
        _pattern = re.compile(r"(?<!\w)" + _escaped + r"(?!\w)", re.IGNORECASE)
    _ALIAS_PATTERNS.append((_pattern, _canonical))


def extract_skills_from_text(text: str) -> list[str]:
    """Extract real skill names from free text using the taxonomy dictionary.

    Returns a deduplicated list of canonical skill names sorted alphabetically.
    """
    if not text or not text.strip():
        return []

    found: set[str] = set()
    for pattern, canonical in _ALIAS_PATTERNS:
        if pattern.search(text):
            found.add(canonical)

    return sorted(found)
