export const metadata = {
  title: 'Terms of Service — Winnow',
  description: 'Winnow terms of service',
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: 800, margin: '0 auto', padding: '40px 20px', fontFamily: 'system-ui' }}>
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> February 2026</p>
      <p>By using Winnow, you agree to these terms.</p>

      <h2>Service Description</h2>
      <p>Winnow is a job matching platform that analyzes your resume, matches you with relevant job opportunities, and generates tailored ATS-optimized resumes. We do not guarantee employment outcomes.</p>

      <h2>Account Responsibilities</h2>
      <p>You are responsible for maintaining the security of your account credentials. You must provide accurate information in your profile and resume.</p>

      <h2>Acceptable Use</h2>
      <p>You agree not to: upload fraudulent resumes, use the service to spam employers, attempt to circumvent usage limits, or reverse-engineer the matching algorithms.</p>

      <h2>Content Ownership</h2>
      <p>You retain ownership of your resume and profile data. By uploading content, you grant Winnow a license to process it for the purpose of providing our services.</p>

      <h2>Subscription and Billing</h2>
      <p>Free accounts have limited features. Paid subscriptions are billed through Stripe. You can cancel anytime via the Stripe Customer Portal. Refunds are handled per Stripe&apos;s policies.</p>

      <h2>AI-Generated Content</h2>
      <p>Tailored resumes and cover letters are generated by AI. While grounded in your actual experience, you are responsible for reviewing all generated content before use. Winnow does not guarantee that generated resumes will pass any specific ATS system.</p>

      <h2>Limitation of Liability</h2>
      <p>Winnow is provided &quot;as is.&quot; We are not liable for job search outcomes, interview results, or hiring decisions. Our maximum liability is limited to the amount you&apos;ve paid in the past 12 months.</p>

      <h2>Termination</h2>
      <p>We may suspend accounts that violate these terms. You may delete your account at any time.</p>

      <h2>Contact</h2>
      <p>Questions? Contact us at <a href="mailto:support@winnowcc.ai">support@winnowcc.ai</a>.</p>
    </main>
  );
}
